Fix #399 #385 #389
systelab/systelab-components pull request #400
Opened 2020-10-02 09:10 UTC by carlosra85

grid: Grid header context menu not working in ag-grid 23 #399
context-menu: Context Menu with child error after close and reopen #385
api-tree-combobox: Favourites not working on Tree Combobox #389

2020-10-02 09:17 UTC, carlosra85 commented on projects/systelab-components/src/lib/combobox/abstract-combobox.component.html
> +        <button type="button" *ngIf="withFavourites && id!=null && (!isTree || (isTree && level))" #favouriteButton
This is the only code changed, rest is reformat

2020-10-05 09:59 UTC, vinyulis requested changes

2020-10-05 09:59 UTC, vinyulis commented on projects/showcase/src/app/components/combobox/showcase-inner-tree-combobox.component.ts
> +	protected toggleFavourite(): void {
Remove this method as it is developed finally in abstract-api-tree

2020-10-05 09:59 UTC, vinyulis commented on projects/systelab-components/src/lib/combobox/abstract-combobox.component.ts
> +				.indexOf(idString) > -1;
includes

2020-10-05 09:59 UTC, vinyulis commented on projects/systelab-components/src/lib/combobox/tree/abstract-api-tree-combobox.component.ts
> +					.indexOf(this.id.toString()
includes

2020-10-05 09:59 UTC, vinyulis commented on projects/systelab-components/src/lib/combobox/tree/abstract-api-tree-combobox.component.ts
> +			.indexOf(data[this.getLevelIdField(1)].toString()) > -1);
includes

2020-10-05 09:59 UTC, vinyulis commented on projects/systelab-components/src/lib/grid/contextmenu/grid-header-context-menu.component.ts
>  	protected existsAtLeastOneActionEnabled(): boolean {
Better return in one line with "?"

2020-10-05 09:59 UTC, vinyulis commented on projects/systelab-components/src/lib/grid/abstract-grid.component.ts
> +		if (this.headerMenu) {
Better return in one line with "?"

2020-10-05 10:04 UTC, carlosra85 commented on projects/systelab-components/src/lib/combobox/tree/abstract-api-tree-combobox.component.ts
> +					.indexOf(this.id.toString()
index is used for splice

2020-10-05 10:48 UTC, vinyulis approved these changes
OK!!. Many thanks!!

2020-10-05 14:42 UTC, oGalceran1 approved these changes
Thanks for your changes

2020-10-07 07:28 UTC, XavierCalvo approved these changes

2020-10-07 08:52 UTC, merged