Bugfix #271 - Usability issue: Drop down options only responding if clicking on the text
systelab/systelab-components pull request #481
Opened 2021-09-16 05:30 UTC by rserra91

# PR Details

## Description

Now the clickable option in dropdown is all label and not just text, this "error" was not in any component, but it exist on dropdown example.. so I change it to don't replicate this issue if someone bases on it.

## Related Issue

https://github.com/systelab/systelab-components/issues/271
## Motivation and Context

Improve components sample
## How Has This Been Tested

Tested manually deploying in local
## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation 
- [ ] I have updated the documentation accordingly (README.md for each UI component)
- [ ] I have added tests to cover my changes (at least 1 spec for each UI component with the same coverage as the master branch)
- [x] All new and existing tests passed
- [ ] A new branch needs to be created from master to evolve previous versions
- [ ] Increase version in package.json following [Semantic Versioning](https://semver.org/)
- [ ] All UI components must be added into the showcase (at least 1 component with the default settings)
- [ ] Add the issue into the right [project](https://github.com/systelab/systelab-components/projects) with the proper status (In progress)

2021-09-20 06:10 UTC, olgapuig requested changes
Thanks for the fixings @rserra91. 
The version in the package.json needs to be increased following semantic versioning.

2021-09-27 08:38 UTC, rserra91 commented
> The version in the package.json needs to be increased following semantic versioning.

already increased on https://github.com/systelab/systelab-components/pull/479

2021-09-27 15:42 UTC, oGalceran1 approved these changes
OK

2021-09-27 18:40 UTC, VictorDeBlas approved these changes

2021-09-30 07:33 UTC, olgapuig approved these changes

2021-10-04 09:00 UTC, merged