Feature 534
systelab/systelab-components pull request #540
Opened 2022-01-11 11:05 UTC by EduAlberdi

# PR Details

Added templates to Yes/No Popup

## Description

With no template parameter
![image](https://user-images.githubusercontent.com/5593621/148924691-09aed4e2-ae37-4a07-95a8-a03bfbf479b9.png)

With 'primary' template
![image](https://user-images.githubusercontent.com/5593621/148924854-bdf0765c-7f55-4782-bad6-9094bf722a6e.png)

With 'outline-primary' template
![image](https://user-images.githubusercontent.com/5593621/148924973-e221d2ca-438d-406c-818d-4d4116092767.png)

With 'warning' template
![image](https://user-images.githubusercontent.com/5593621/148925148-abb303d1-174a-49d6-a8a0-523151c5e0b0.png)

With 'outline-warning' template
![image](https://user-images.githubusercontent.com/5593621/148925187-87e0be42-4a37-483c-819b-438ca2cef24b.png)

With 'danger' template
![image](https://user-images.githubusercontent.com/5593621/148925237-7af6c3a0-9769-4bdf-8d28-0affa801587a.png)

With 'outline-danger' template
![image](https://user-images.githubusercontent.com/5593621/148925269-b9a80e61-acc4-41f8-b9dc-e91ce656dda1.png)

## Related Issue

#534 

## How Has This Been Tested

Only cosmetic changes

## Types of changes

- [ x ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ x ] I have read the **CONTRIBUTING** document
- [ x ] My code follows the code style of this project
- [ x ] My change requires a change to the documentation 
- [ x ] I have updated the documentation accordingly (README.md for each UI component)
- [] I have added tests to cover my changes (at least 1 spec for each UI component with the same coverage as the master branch)
- [ ] All new and existing tests passed
- [ ] A new branch needs to be created from master to evolve previous versions
- [ x ] Increase version in package.json following [Semantic Versioning](https://semver.org/)
- [ x ] All UI components must be added into the showcase (at least 1 component with the default settings)
- [ x ] Add the issue into the right [project](https://github.com/systelab/systelab-components/projects) with the proper status (In progress)

2022-01-11 11:45 UTC, OscarDeDios approved these changes

2022-01-11 14:58 UTC, Saul98 approved these changes

2022-01-12 07:38 UTC, olgapuig requested changes
Increase the coverage in the spec because codecov fails
Increase the version as minor in the package.json

2022-01-12 11:27 UTC, OscarDeDios approved these changes

2022-01-12 12:57 UTC, Saul98 approved these changes

2022-01-12 13:07 UTC, olgapuig approved these changes
Thanks for increasing the coverage @EduAlberdi, good job!

2022-01-12 13:07 UTC, merged