Bugfix 559
systelab/systelab-components pull request #560
Opened 2022-02-03 11:12 UTC by EduAlberdi

# PR Details

## Description

## Related Issue

#559 

## Motivation and Context

## How Has This Been Tested

Cosmetic changes

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation 
- [ ] I have updated the documentation accordingly (README.md for each UI component)
- [ ] I have added tests to cover my changes (at least 1 spec for each UI component with the same coverage as the master branch)
- [ ] All new and existing tests passed
- [ ] A new branch needs to be created from master to evolve previous versions
- [x] Increase version in package.json following [Semantic Versioning](https://semver.org/)
- [ ] All UI components must be added into the showcase (at least 1 component with the default settings)
- [ ] Add the issue into the right [project](https://github.com/systelab/systelab-components/projects) with the proper status (In progress)

2022-02-03 13:48 UTC, olgapuig approved these changes

2022-02-03 13:49 UTC, olgapuig requested changes
@EduAlberdi thanks for the fix but the style needs to be set for the modern style.

2022-02-03 13:58 UTC, EduAlberdi commented
Changed

2022-02-04 07:19 UTC, Saul98 submitted a review, later dismissed

2022-02-04 07:54 UTC, olgapuig approved these changes

2022-02-04 08:07 UTC, Saul98 approved these changes

2022-02-07 09:04 UTC, Saul98 approved these changes

2022-02-07 10:19 UTC, olgapuig submitted a review, later dismissed

2022-02-07 11:39 UTC, joangaya submitted a review, later dismissed

2022-02-08 16:41 UTC, OscarDeDios approved these changes

2022-02-09 08:03 UTC, Saul98 approved these changes

2022-02-09 10:33 UTC, olgapuig approved these changes

2022-02-09 10:34 UTC, merged