842-allow-having-transparent-header-for-image-viewer
systelab/systelab-components pull request #843
Opened 2024-03-21 11:09 UTC by p-riera

# PR Details

Added functionality

## Description

New input for image viewer component to allow it having a transparent header.
Added showcase option to enable/disable this option and test

## Related Issue

#842 

## Motivation and Context

It allows setting header to transparent for small images that could get covered by header

## How Has This Been Tested

showcase, manual test

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation 
- [x] I have updated the documentation accordingly (README.md for each UI component)
- [ ] I have added tests to cover my changes (at least 1 spec for each UI component with the same coverage as the master branch)
- [x] All new and existing tests passed
- [ ] A new branch needs to be created from master to evolve previous versions
- [x] Increase version in package.json following [Semantic Versioning](https://semver.org/)
- [x] All UI components must be added into the showcase (at least 1 component with the default settings)
- [x] Add the issue into the right [project](https://github.com/systelab/systelab-components/projects) with the proper status (In progress)

2024-03-21 17:21 UTC, alfonsserra requested changes

2024-03-21 17:21 UTC, alfonsserra commented on projects/systelab-components/src/lib/image-viewer/image-viewer.component.ts
> +	@Input() public setTransparentBackgroundForButtons = false;
Use a name and not a verb for an Input attribute.

2024-03-21 17:21 UTC, alfonsserra commented on projects/systelab-components/src/lib/image-viewer/image-viewer.component.spec.ts
> +	public setTransparentBackgroundForButtons = false;
Use a name and not a verb for a field.

2024-03-21 17:21 UTC, alfonsserra commented on projects/showcase/src/app/components/image-viewer/showcase-image-viewer.component.ts
> +	public setTransparent = false;
Use names not verbs.

2024-03-22 12:33 UTC, OscarDeDios approved these changes

2024-03-22 12:36 UTC, alfonsserra approved these changes

2024-03-22 12:36 UTC, merged